### ISSUE TITLE
Filter list not showing on Windows

### ISSUE THREAD

**Issue by enci** [mlabbe/nativefiledialog#58] opened 2018-10-25 15:08 UTC
The filter list is not populated with text on Windows 10 (neither for the save or the open dialog). The files are, however, still being filtered correctly by the chosen filter, it's just that the filters are not displayed in the drop-down.

![savedialogcapture](https://user-images.githubusercontent.com/762458/47509969-7296e680-d877-11e8-959f-a97d4b32ec33.PNG)

**Comment by deltabeard** [comment] 2018-12-03 19:30
I think this is a duplicate of https://github.com/mlabbe/nativefiledialog/issues/51 where a [patch](https://github.com/GarageGames/Torque3D/pull/2270/files) is given, which I've [tested working](https://github.com/deltabeard/peanut-gb/commit/1b605378bed677ce570e8e757cf8b278672343a8) on Windows 10 just now.

**Comment by mlabbe** [comment] 2018-12-30 19:52
Duplicate of #51

**Closed by mlabbe** 2018-12-30 19:52 UTC
